/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tournamentSol from "./Tournament.sol";
export type { tournamentSol };
export type { Greeter } from "./Greeter";
export type { TokenManager } from "./TokenManager";
export type { WordChainAdmin } from "./WordChainAdmin";
export type { WordChainToken } from "./WordChainToken";
