/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tournamentSol from "./Tournament.sol";
export { Greeter__factory } from "./Greeter__factory";
export { TokenManager__factory } from "./TokenManager__factory";
export { WordChainAdmin__factory } from "./WordChainAdmin__factory";
export { WordChainToken__factory } from "./WordChainToken__factory";
